
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 0 1 2  --importance_threshold 0.75 --edgefile cchfl_0-2_75.dat --dotfile cchfl_0-2_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 3 4 5  --importance_threshold 0.75 --edgefile cchfl_3-5_75.dat --dotfile cchfl_3-5_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 6 7 8  --importance_threshold 0.75 --edgefile cchfl_6-8_75.dat --dotfile cchfl_6-8_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 9 10 11  --importance_threshold 0.75 --edgefile cchfl_9-11_75.dat --dotfile cchfl_9-11_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 12 13 14  --importance_threshold 0.75 --edgefile cchfl_12-14_75.dat --dotfile cchfl_12-14_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 15 16 17  --importance_threshold 0.75 --edgefile cchfl_15-17_75.dat --dotfile cchfl_15-17_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 18 19 20  --importance_threshold 0.75 --edgefile cchfl_18-20_75.dat --dotfile cchfl_18-20_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 21 22 23  --importance_threshold 0.75 --edgefile cchfl_21-23_75.dat --dotfile cchfl_21-23_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 24 25 26  --importance_threshold 0.75 --edgefile cchfl_24-26_75.dat --dotfile cchfl_24-26_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 27 28 29  --importance_threshold 0.75 --edgefile cchfl_27-29_75.dat --dotfile cchfl_27-29_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 30 31 32  --importance_threshold 0.75 --edgefile cchfl_30-32_75.dat --dotfile cchfl_30-32_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 33 34 35  --importance_threshold 0.75 --edgefile cchfl_33-35_75.dat --dotfile cchfl_33-35_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 36 37 38  --importance_threshold 0.75 --edgefile cchfl_36-38_75.dat --dotfile cchfl_36-38_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 39 40 41  --importance_threshold 0.75 --edgefile cchfl_39-41_75.dat --dotfile cchfl_39-41_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 42 43 44  --importance_threshold 0.75 --edgefile cchfl_42-44_75.dat --dotfile cchfl_42-44_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 45 46 47  --importance_threshold 0.75 --edgefile cchfl_45-47_75.dat --dotfile cchfl_45-47_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 48 49 50  --importance_threshold 0.75 --edgefile cchfl_48-50_75.dat --dotfile cchfl_48-50_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 51 52 53  --importance_threshold 0.75 --edgefile cchfl_51-53_75.dat --dotfile cchfl_51-53_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 54 55 56  --importance_threshold 0.75 --edgefile cchfl_54-56_75.dat --dotfile cchfl_54-56_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 57 58 59  --importance_threshold 0.75 --edgefile cchfl_57-59_75.dat --dotfile cchfl_57-59_75.dot --tree_prefix 75_cchfl
