
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 300 301 302  --importance_threshold 0.75 --edgefile cchfl_300-302_75.dat --dotfile cchfl_300-302_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 303 304 305  --importance_threshold 0.75 --edgefile cchfl_303-305_75.dat --dotfile cchfl_303-305_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 306 307 308  --importance_threshold 0.75 --edgefile cchfl_306-308_75.dat --dotfile cchfl_306-308_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 309 310 311  --importance_threshold 0.75 --edgefile cchfl_309-311_75.dat --dotfile cchfl_309-311_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 312 313 314  --importance_threshold 0.75 --edgefile cchfl_312-314_75.dat --dotfile cchfl_312-314_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 315 316 317  --importance_threshold 0.75 --edgefile cchfl_315-317_75.dat --dotfile cchfl_315-317_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 318 319 320  --importance_threshold 0.75 --edgefile cchfl_318-320_75.dat --dotfile cchfl_318-320_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 321 322 323  --importance_threshold 0.75 --edgefile cchfl_321-323_75.dat --dotfile cchfl_321-323_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 324 325 326  --importance_threshold 0.75 --edgefile cchfl_324-326_75.dat --dotfile cchfl_324-326_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 327 328 329  --importance_threshold 0.75 --edgefile cchfl_327-329_75.dat --dotfile cchfl_327-329_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 330 331 332  --importance_threshold 0.75 --edgefile cchfl_330-332_75.dat --dotfile cchfl_330-332_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 333 334 335  --importance_threshold 0.75 --edgefile cchfl_333-335_75.dat --dotfile cchfl_333-335_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 336 337 338  --importance_threshold 0.75 --edgefile cchfl_336-338_75.dat --dotfile cchfl_336-338_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 339 340 341  --importance_threshold 0.75 --edgefile cchfl_339-341_75.dat --dotfile cchfl_339-341_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 342 343 344  --importance_threshold 0.75 --edgefile cchfl_342-344_75.dat --dotfile cchfl_342-344_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 345 346 347  --importance_threshold 0.75 --edgefile cchfl_345-347_75.dat --dotfile cchfl_345-347_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 348 349 350  --importance_threshold 0.75 --edgefile cchfl_348-350_75.dat --dotfile cchfl_348-350_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 351 352 353  --importance_threshold 0.75 --edgefile cchfl_351-353_75.dat --dotfile cchfl_351-353_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 354 355 356  --importance_threshold 0.75 --edgefile cchfl_354-356_75.dat --dotfile cchfl_354-356_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 357 358 359  --importance_threshold 0.75 --edgefile cchfl_357-359_75.dat --dotfile cchfl_357-359_75.dot --tree_prefix 75_cchfl
