
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 360 361 362  --importance_threshold 0.75 --edgefile cchfl_360-362_75.dat --dotfile cchfl_360-362_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 363 364 365  --importance_threshold 0.75 --edgefile cchfl_363-365_75.dat --dotfile cchfl_363-365_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 366 367 368  --importance_threshold 0.75 --edgefile cchfl_366-368_75.dat --dotfile cchfl_366-368_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 369 370 371  --importance_threshold 0.75 --edgefile cchfl_369-371_75.dat --dotfile cchfl_369-371_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 372 373 374  --importance_threshold 0.75 --edgefile cchfl_372-374_75.dat --dotfile cchfl_372-374_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 375 376 377  --importance_threshold 0.75 --edgefile cchfl_375-377_75.dat --dotfile cchfl_375-377_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 378 379 380  --importance_threshold 0.75 --edgefile cchfl_378-380_75.dat --dotfile cchfl_378-380_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 381 382 383  --importance_threshold 0.75 --edgefile cchfl_381-383_75.dat --dotfile cchfl_381-383_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 384 385 386  --importance_threshold 0.75 --edgefile cchfl_384-386_75.dat --dotfile cchfl_384-386_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 387 388 389  --importance_threshold 0.75 --edgefile cchfl_387-389_75.dat --dotfile cchfl_387-389_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 390 391 392  --importance_threshold 0.75 --edgefile cchfl_390-392_75.dat --dotfile cchfl_390-392_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 393 394 395  --importance_threshold 0.75 --edgefile cchfl_393-395_75.dat --dotfile cchfl_393-395_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 396 397 398  --importance_threshold 0.75 --edgefile cchfl_396-398_75.dat --dotfile cchfl_396-398_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 399  --importance_threshold 0.75 --edgefile cchfl_399-399_75.dat --dotfile cchfl_399-399_75.dot --tree_prefix 75_cchfl
