
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 60 61 62  --importance_threshold 0.75 --edgefile cchfl_60-62_75.dat --dotfile cchfl_60-62_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 63 64 65  --importance_threshold 0.75 --edgefile cchfl_63-65_75.dat --dotfile cchfl_63-65_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 66 67 68  --importance_threshold 0.75 --edgefile cchfl_66-68_75.dat --dotfile cchfl_66-68_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 69 70 71  --importance_threshold 0.75 --edgefile cchfl_69-71_75.dat --dotfile cchfl_69-71_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 72 73 74  --importance_threshold 0.75 --edgefile cchfl_72-74_75.dat --dotfile cchfl_72-74_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 75 76 77  --importance_threshold 0.75 --edgefile cchfl_75-77_75.dat --dotfile cchfl_75-77_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 78 79 80  --importance_threshold 0.75 --edgefile cchfl_78-80_75.dat --dotfile cchfl_78-80_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 81 82 83  --importance_threshold 0.75 --edgefile cchfl_81-83_75.dat --dotfile cchfl_81-83_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 84 85 86  --importance_threshold 0.75 --edgefile cchfl_84-86_75.dat --dotfile cchfl_84-86_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 87 88 89  --importance_threshold 0.75 --edgefile cchfl_87-89_75.dat --dotfile cchfl_87-89_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 90 91 92  --importance_threshold 0.75 --edgefile cchfl_90-92_75.dat --dotfile cchfl_90-92_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 93 94 95  --importance_threshold 0.75 --edgefile cchfl_93-95_75.dat --dotfile cchfl_93-95_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 96 97 98  --importance_threshold 0.75 --edgefile cchfl_96-98_75.dat --dotfile cchfl_96-98_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 99 100 101  --importance_threshold 0.75 --edgefile cchfl_99-101_75.dat --dotfile cchfl_99-101_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 102 103 104  --importance_threshold 0.75 --edgefile cchfl_102-104_75.dat --dotfile cchfl_102-104_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 105 106 107  --importance_threshold 0.75 --edgefile cchfl_105-107_75.dat --dotfile cchfl_105-107_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 108 109 110  --importance_threshold 0.75 --edgefile cchfl_108-110_75.dat --dotfile cchfl_108-110_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 111 112 113  --importance_threshold 0.75 --edgefile cchfl_111-113_75.dat --dotfile cchfl_111-113_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 114 115 116  --importance_threshold 0.75 --edgefile cchfl_114-116_75.dat --dotfile cchfl_114-116_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 117 118 119  --importance_threshold 0.75 --edgefile cchfl_117-119_75.dat --dotfile cchfl_117-119_75.dot --tree_prefix 75_cchfl
