
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 120 121 122  --importance_threshold 0.75 --edgefile cchfl_120-122_75.dat --dotfile cchfl_120-122_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 123 124 125  --importance_threshold 0.75 --edgefile cchfl_123-125_75.dat --dotfile cchfl_123-125_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 126 127 128  --importance_threshold 0.75 --edgefile cchfl_126-128_75.dat --dotfile cchfl_126-128_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 129 130 131  --importance_threshold 0.75 --edgefile cchfl_129-131_75.dat --dotfile cchfl_129-131_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 132 133 134  --importance_threshold 0.75 --edgefile cchfl_132-134_75.dat --dotfile cchfl_132-134_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 135 136 137  --importance_threshold 0.75 --edgefile cchfl_135-137_75.dat --dotfile cchfl_135-137_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 138 139 140  --importance_threshold 0.75 --edgefile cchfl_138-140_75.dat --dotfile cchfl_138-140_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 141 142 143  --importance_threshold 0.75 --edgefile cchfl_141-143_75.dat --dotfile cchfl_141-143_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 144 145 146  --importance_threshold 0.75 --edgefile cchfl_144-146_75.dat --dotfile cchfl_144-146_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 147 148 149  --importance_threshold 0.75 --edgefile cchfl_147-149_75.dat --dotfile cchfl_147-149_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 150 151 152  --importance_threshold 0.75 --edgefile cchfl_150-152_75.dat --dotfile cchfl_150-152_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 153 154 155  --importance_threshold 0.75 --edgefile cchfl_153-155_75.dat --dotfile cchfl_153-155_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 156 157 158  --importance_threshold 0.75 --edgefile cchfl_156-158_75.dat --dotfile cchfl_156-158_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 159 160 161  --importance_threshold 0.75 --edgefile cchfl_159-161_75.dat --dotfile cchfl_159-161_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 162 163 164  --importance_threshold 0.75 --edgefile cchfl_162-164_75.dat --dotfile cchfl_162-164_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 165 166 167  --importance_threshold 0.75 --edgefile cchfl_165-167_75.dat --dotfile cchfl_165-167_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 168 169 170  --importance_threshold 0.75 --edgefile cchfl_168-170_75.dat --dotfile cchfl_168-170_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 171 172 173  --importance_threshold 0.75 --edgefile cchfl_171-173_75.dat --dotfile cchfl_171-173_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 174 175 176  --importance_threshold 0.75 --edgefile cchfl_174-176_75.dat --dotfile cchfl_174-176_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 177 178 179  --importance_threshold 0.75 --edgefile cchfl_177-179_75.dat --dotfile cchfl_177-179_75.dot --tree_prefix 75_cchfl
