
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 180 181 182  --importance_threshold 0.75 --edgefile cchfl_180-182_75.dat --dotfile cchfl_180-182_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 183 184 185  --importance_threshold 0.75 --edgefile cchfl_183-185_75.dat --dotfile cchfl_183-185_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 186 187 188  --importance_threshold 0.75 --edgefile cchfl_186-188_75.dat --dotfile cchfl_186-188_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 189 190 191  --importance_threshold 0.75 --edgefile cchfl_189-191_75.dat --dotfile cchfl_189-191_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 192 193 194  --importance_threshold 0.75 --edgefile cchfl_192-194_75.dat --dotfile cchfl_192-194_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 195 196 197  --importance_threshold 0.75 --edgefile cchfl_195-197_75.dat --dotfile cchfl_195-197_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 198 199 200  --importance_threshold 0.75 --edgefile cchfl_198-200_75.dat --dotfile cchfl_198-200_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 201 202 203  --importance_threshold 0.75 --edgefile cchfl_201-203_75.dat --dotfile cchfl_201-203_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 204 205 206  --importance_threshold 0.75 --edgefile cchfl_204-206_75.dat --dotfile cchfl_204-206_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 207 208 209  --importance_threshold 0.75 --edgefile cchfl_207-209_75.dat --dotfile cchfl_207-209_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 210 211 212  --importance_threshold 0.75 --edgefile cchfl_210-212_75.dat --dotfile cchfl_210-212_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 213 214 215  --importance_threshold 0.75 --edgefile cchfl_213-215_75.dat --dotfile cchfl_213-215_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 216 217 218  --importance_threshold 0.75 --edgefile cchfl_216-218_75.dat --dotfile cchfl_216-218_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 219 220 221  --importance_threshold 0.75 --edgefile cchfl_219-221_75.dat --dotfile cchfl_219-221_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 222 223 224  --importance_threshold 0.75 --edgefile cchfl_222-224_75.dat --dotfile cchfl_222-224_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 225 226 227  --importance_threshold 0.75 --edgefile cchfl_225-227_75.dat --dotfile cchfl_225-227_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 228 229 230  --importance_threshold 0.75 --edgefile cchfl_228-230_75.dat --dotfile cchfl_228-230_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 231 232 233  --importance_threshold 0.75 --edgefile cchfl_231-233_75.dat --dotfile cchfl_231-233_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 234 235 236  --importance_threshold 0.75 --edgefile cchfl_234-236_75.dat --dotfile cchfl_234-236_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 237 238 239  --importance_threshold 0.75 --edgefile cchfl_237-239_75.dat --dotfile cchfl_237-239_75.dot --tree_prefix 75_cchfl
