
python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 240 241 242  --importance_threshold 0.75 --edgefile cchfl_240-242_75.dat --dotfile cchfl_240-242_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 243 244 245  --importance_threshold 0.75 --edgefile cchfl_243-245_75.dat --dotfile cchfl_243-245_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 246 247 248  --importance_threshold 0.75 --edgefile cchfl_246-248_75.dat --dotfile cchfl_246-248_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 249 250 251  --importance_threshold 0.75 --edgefile cchfl_249-251_75.dat --dotfile cchfl_249-251_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 252 253 254  --importance_threshold 0.75 --edgefile cchfl_252-254_75.dat --dotfile cchfl_252-254_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 255 256 257  --importance_threshold 0.75 --edgefile cchfl_255-257_75.dat --dotfile cchfl_255-257_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 258 259 260  --importance_threshold 0.75 --edgefile cchfl_258-260_75.dat --dotfile cchfl_258-260_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 261 262 263  --importance_threshold 0.75 --edgefile cchfl_261-263_75.dat --dotfile cchfl_261-263_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 264 265 266  --importance_threshold 0.75 --edgefile cchfl_264-266_75.dat --dotfile cchfl_264-266_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 267 268 269  --importance_threshold 0.75 --edgefile cchfl_267-269_75.dat --dotfile cchfl_267-269_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 270 271 272  --importance_threshold 0.75 --edgefile cchfl_270-272_75.dat --dotfile cchfl_270-272_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 273 274 275  --importance_threshold 0.75 --edgefile cchfl_273-275_75.dat --dotfile cchfl_273-275_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 276 277 278  --importance_threshold 0.75 --edgefile cchfl_276-278_75.dat --dotfile cchfl_276-278_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 279 280 281  --importance_threshold 0.75 --edgefile cchfl_279-281_75.dat --dotfile cchfl_279-281_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 282 283 284  --importance_threshold 0.75 --edgefile cchfl_282-284_75.dat --dotfile cchfl_282-284_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 285 286 287  --importance_threshold 0.75 --edgefile cchfl_285-287_75.dat --dotfile cchfl_285-287_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 288 289 290  --importance_threshold 0.75 --edgefile cchfl_288-290_75.dat --dotfile cchfl_288-290_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 291 292 293  --importance_threshold 0.75 --edgefile cchfl_291-293_75.dat --dotfile cchfl_291-293_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 294 295 296  --importance_threshold 0.75 --edgefile cchfl_294-296_75.dat --dotfile cchfl_294-296_75.dot --tree_prefix 75_cchfl

python /home/ishanu/ZED/Research/mlexpress_/pycode/qNet.py --file ../../qnet_/data/cchfl_train.csv --filex ../../qnet_/data/cchfl_test.csv  --varimp True --response 297 298 299  --importance_threshold 0.75 --edgefile cchfl_297-299_75.dat --dotfile cchfl_297-299_75.dot --tree_prefix 75_cchfl
